<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Payment Gateway Project Test Automation Regression Test Suite" duration-ms="107046" started-at="2018-04-30T05:42:23Z" finished-at="2018-04-30T05:44:10Z">
    <groups>
    </groups>
    <test name="Payment Gateway Test Cases" duration-ms="107046" started-at="2018-04-30T05:42:23Z" finished-at="2018-04-30T05:44:10Z">
      <class name="com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="setUp" is-config="true" duration-ms="7484" started-at="2018-04-30T05:42:23Z" finished-at="2018-04-30T05:42:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPreAuthForNewCustomerSingleDomain()[pri:1, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="verifyPreAuthForNewCustomerSingleDomain" duration-ms="17179" started-at="2018-04-30T05:42:31Z" finished-at="2018-04-30T05:42:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order is not completed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order is not completed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest.verifyPreAuthForNewCustomerSingleDomain(DomainRegistrationPreAuthTest.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPreAuthForNewCustomerSingleDomain -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="733" started-at="2018-04-30T05:42:48Z" finished-at="2018-04-30T05:42:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="setUp" is-config="true" duration-ms="6465" started-at="2018-04-30T05:42:49Z" finished-at="2018-04-30T05:42:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPreAuthForExistingCustomerMultipleDomains()[pri:2, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="verifyPreAuthForExistingCustomerMultipleDomains" duration-ms="19383" started-at="2018-04-30T05:42:55Z" finished-at="2018-04-30T05:43:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order is not completed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order is not completed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest.verifyPreAuthForExistingCustomerMultipleDomains(DomainRegistrationPreAuthTest.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPreAuthForExistingCustomerMultipleDomains -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="998" started-at="2018-04-30T05:43:15Z" finished-at="2018-04-30T05:43:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="setUp" is-config="true" duration-ms="6162" started-at="2018-04-30T05:43:16Z" finished-at="2018-04-30T05:43:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPreAuthForNewCustomerSingleProduct()[pri:3, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="verifyPreAuthForNewCustomerSingleProduct" duration-ms="18413" started-at="2018-04-30T05:43:22Z" finished-at="2018-04-30T05:43:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order is not completed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order is not completed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest.verifyPreAuthForNewCustomerSingleProduct(DomainRegistrationPreAuthTest.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPreAuthForNewCustomerSingleProduct -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="774" started-at="2018-04-30T05:43:40Z" finished-at="2018-04-30T05:43:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="setUp" is-config="true" duration-ms="6376" started-at="2018-04-30T05:43:41Z" finished-at="2018-04-30T05:43:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyPreAuthForExistingCustomerMultipleProducts()[pri:4, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="verifyPreAuthForExistingCustomerMultipleProducts" duration-ms="22300" started-at="2018-04-30T05:43:47Z" finished-at="2018-04-30T05:44:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Order is not completed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Order is not completed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest.verifyPreAuthForExistingCustomerMultipleProducts(DomainRegistrationPreAuthTest.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPreAuthForExistingCustomerMultipleProducts -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="730" started-at="2018-04-30T05:44:10Z" finished-at="2018-04-30T05:44:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.paymentgateway.ui.dmz.testcases.DomainRegistrationPreAuthTest -->
    </test> <!-- Payment Gateway Test Cases -->
  </suite> <!-- Payment Gateway Project Test Automation Regression Test Suite -->
</testng-results>
